"""Hybrid Stabilizer-MPO evolutor"""

from dataclasses import dataclass

import numpy as np
from qibo import Circuit

from mpstab.backends.stabilizers.abstract import StabilizersEngine
from mpstab.backends.stabilizers.stim import StimEngine
from mpstab.evolutors.tensor_network.circuit_mps import CircuitMPS
from mpstab.evolutors.tensor_network.operators.observables import PauliMPO
from mpstab.evolutors.utils import gate2generator
from mpstab.models.ansatze import Ansatz


@dataclass
class HSMPO:
    """
    Construct an hybrid stabilizer MPO surrogate of a given quantum circuit.

    Args:
        circuit (mpstab.targets.Ansatz): given quantum circuit in the form of a
            mpstab ansatz class.
        initial_state (qibo.models.Circuit): quantum circuit preparing the inital
            state. It has to be composed of single-qubit gates only.
    """

    ansatz: Ansatz
    max_bond_dimension: int = None
    initial_state: Circuit = None

    def __post_init__(self):
        # Initial state is zero by default
        if self.initial_state is None:
            self.initial_state = Circuit(self.ansatz.nqubits)

        # Add the initial state, which is |0> by default
        self._init_tn(self.max_bond_dimension)

        # Initialize engines
        # Default stabilizers engine is Stim
        self.set_engines()

    def _init_tn(self, max_bond_dimension: int | None = None):
        """
        Initialize the HybridEvolutor's tensor network to the factorized state specified by the initial state circuit.
        """

        amplitudes = []
        for q in range(self.nqubits):

            light_circ, light_dict = self.initial_state.light_cone(q)

            # Check whether the initial state is constructed properly
            # (with one-qubit gates only)
            if len(light_dict.items()) > 1:
                raise ValueError(
                    "Ensure only 1-qubit gates compose the initial state preparation circuit."
                )

            # Add the initial state tensor
            amplitudes.append(light_circ().state())

        self.mps = CircuitMPS(
            n=self.nqubits,
            initial_state=np.array(amplitudes),
            max_bond_dimension=max_bond_dimension,
        )

    def expectation(self, observable: str) -> float:
        """
        Compute the expectation value of an observable with respect to the
        full ansatz circuit (no partitioning).

        Args:
            observable (str): Pauli string observable, e.g. "ZIZX".

        Returns:
            float: Expectation value ⟨ψ|O|ψ⟩.
        """
        # Reset MPS to initial state
        self._init_tn(self.max_bond_dimension)

        expval = self.expectation_from_partition(
            observable, replacement_probability=0.0
        )[0]

        return expval

    @property
    def nqubits(self):
        return self.ansatz.circuit.nqubits

    def expectation_from_partition(
        self,
        observable: str,
        replacement_probability: float,
        replacement_method: str = "closest",
        return_partitions: bool = False,
    ):
        """
        Sample a lower-magic circuit from the ansatz, and compute its expectation value w.r.t. the observable.
        The lower-magic circuit is generated by selectively dropping magic gates with a certain rate, leaving
        only a fraction per partition. Partitioning is performed according to the Ansatz specifications.

        If specified, returns the partitions used to generate the lower-magic circuit.
        """

        # Partitionate circuit
        (magic_gates, clifford_circuit), full_circuit = (
            self.ansatz.partitionate_circuit(
                replacement_probability=replacement_probability,
                replacement_method=replacement_method,
            )
        )

        # check the stab layers, might be wrong
        for k, magic_gate in magic_gates:
            clifford_subcircuit = self._clifford_subcircuit(clifford_circuit, k)
            generator = self._conjugate_generator(magic_gate, clifford_subcircuit)
            self.mps.pauli_rot(generator, magic_gate.parameters[0])

        # Compute the conjugate of the observable
        new_observable = self.stab_engine.backpropagate(
            observable=observable, clifford_circuit=clifford_circuit
        )

        # Collect partitions into a dictionary in case we want to return it
        if return_partitions:
            partitions = {
                "magic_gates": magic_gates,
                "only_cliffords": clifford_circuit,
                "full_circuit": full_circuit,
            }
        else:
            partitions = None

        return self.mps.expval(PauliMPO(new_observable)), partitions

    def _conjugate_generator(self, gate, clifford_circuit):
        """Conjugate a given gate generator by a sequence of Clifford circuits."""

        if gate.name not in ["rx", "ry", "rz"]:
            raise ValueError("mpstab currently supports only rotational gates.")

        generator = "".join(
            [
                gate2generator[gate.name] if q in gate.target_qubits else "I"
                for q in range(self.nqubits)
            ]
        )
        return self.stab_engine.backpropagate(generator, clifford_circuit)

    def set_engines(self, stab_engine: StabilizersEngine = None):
        """
        Set stabilizers evolution engine.

        args:
            stab_engine (StabilizerEngine): it can be StimEngine or NativeStabilizerEngine.
                Each engine is an object in mpstab and we expect here `stab_engine` to be
                initialized.
        """
        if stab_engine is None:
            stab_engine = StimEngine()

        if not isinstance(stab_engine, StabilizersEngine):
            raise ValueError(f"Provided engine {stab_engine} is not supported.")

        self.stab_engine = stab_engine

    def _clifford_subcircuit(self, clifford_circuit: Circuit, k: int = 0) -> Circuit:
        """Return a sub-circuit of a given Clifford circuit, cut at index `k`."""
        cut_queue = (
            clifford_circuit.queue[:k] if k is not None else clifford_circuit.queue
        )

        clifford_subcircuit = Circuit(clifford_circuit.nqubits)
        for gate in cut_queue:
            clifford_subcircuit.add(gate)

        return clifford_subcircuit
