"""Hybrid Stabilizer-MPO evolutor"""

from dataclasses import dataclass

import numpy as np
from qibo import Circuit

from mpstab.evolutors.stabilizer import tableaus
from mpstab.evolutors.stabilizer.pauli_string import Pauli
from mpstab.evolutors.tensor_network.circuit_mps import CircuitMPS
from mpstab.evolutors.tensor_network.operators.observables import PauliMPO
from mpstab.evolutors.utils import gate2generator, gate2tableau
from mpstab.targets.ansatze import Ansatz


@dataclass
class HybridSurrogate:
    """
    Construct an hybrid stabilizer MPO surrogate of a given quantum circuit.

    Args:
        circuit (mpstab.targets.Ansatz): given quantum circuit in the form of a
            mpstab ansatz class.
        initial_state (qibo.models.Circuit): quantum circuit preparing the inital
            state. It has to be composed of single-qubit gates only.
    """

    ansatz: Ansatz
    max_bond_dimension: int = None
    initial_state: Circuit = None

    def __post_init__(self):
        # Initial state is zero by default
        if self.initial_state is None:
            self.initial_state = Circuit(self.ansatz.nqubits)

        # Add the initial state, which is |0> by default
        self._init_tn(self.max_bond_dimension)

    def _init_tn(self, max_bond_dimension: int | None = None):
        """
        Initialize the HybridEvolutor's tensor network to the factorized state specified by the initial state circuit.
        """

        amplitudes = []
        for q in range(self.nqubits):

            light_circ, light_dict = self.initial_state.light_cone(q)

            # Check whether the initial state is constructed properly
            # (with one-qubit gates only)
            if len(light_dict.items()) > 1:
                raise ValueError(
                    "Ensure only 1-qubit gates compose the initial state preparation circuit."
                )

            # Add the initial state tensor
            amplitudes.append(light_circ().state())

        self.mps = CircuitMPS(
            n=self.nqubits,
            initial_state=np.array(amplitudes),
            max_bond_dimension=max_bond_dimension,
        )

    def expectation(self, observable: str) -> float:
        """
        Compute the expectation value of an observable with respect to the
        full ansatz circuit (no partitioning).

        Args:
            observable (str): Pauli string observable, e.g. "ZIZX".

        Returns:
            float: Expectation value ⟨ψ|O|ψ⟩.
        """
        # Reset MPS to initial state
        self._init_tn(self.max_bond_dimension)

        expval = self.expectation_from_partition(
            observable, replacement_probability=0.0
        )[0]

        return expval

    @property
    def nqubits(self):
        return self.ansatz.circuit.nqubits

    def expectation_from_partition(
        self,
        observable: str,
        replacement_probability: float,
        replacement_method: str = "closest",
        return_partitions: bool = False,
    ):
        """
        Sample a lower-magic circuit from the ansatz, and compute its expectation value w.r.t. the observable.
        The lower-magic circuit is generated by selectively dropping magic gates with a certain rate, leaving
        only a fraction per partition. Partitioning is performed according to the Ansatz specifications.

        If specified, returns the partitions used to generate the lower-magic circuit.
        """

        # Partitionate circuit
        (magic_gates, clifford_circuit), full_circuit = (
            self.ansatz.partitionate_circuit(
                replacement_probability=replacement_probability,
                replacement_method=replacement_method,
            )
        )

        # check the stab layers, might be wrong
        for k, magic_gate in magic_gates:

            generator = self._conjugate_generator(magic_gate, clifford_circuit, k)
            self.mps.pauli_rot(generator, magic_gate.parameters[0])

        # Compute the conjugate of the observable
        new_observable = self.backpropagate_pauli(observable, clifford_circuit)

        # Collect partitions into a dictionary in case we want to return it
        if return_partitions:
            partitions = {
                "magic_gates": magic_gates,
                "only_cliffords": clifford_circuit,
                "full_circuit": full_circuit,
            }
        else:
            partitions = None

        return self.mps.expval(PauliMPO(new_observable)), partitions

    def samples(self, nshots: int = 1024) -> np.ndarray:
        """
        Sample bitstrings from the hybrid stabilizer-MPO state.

        Args:
            nshots (int): number of samples to draw.

        Returns:
            np.ndarray: array of shape (nshots, nqubits) with 0/1 measurement outcomes.
        """
        # Reset MPS to initial state
        self._init_tn(self.max_bond_dimension)

        return self.mps.sample(nshots)

    def _conjugate_generator(self, gate, clifford_circuit, k):
        """Conjugate a given gate generator by a sequence of Clifford circuits."""

        if gate.name not in ["rx", "ry", "rz"]:
            raise ValueError("mpstab currently supports only rotational gates.")

        generator = "".join(
            [
                gate2generator[gate.name] if q in gate.target_qubits else "I"
                for q in range(self.nqubits)
            ]
        )
        return self.backpropagate_pauli(generator, clifford_circuit, k)

    def backpropagate_pauli(
        self, observable: str, stabilizer_circuit: Circuit, k: int = None
    ):
        """
        Process a given Pauli string applying a `stabilizer_circuit` in Heisenberg picture.
        """
        # Construct the propagator and apply the inverse of the circuit gate by gate
        propagator = Pauli(observable)

        # Cut the circuit queue to include only the appropriate clifford gates
        cut_queue = (
            stabilizer_circuit.queue[:k] if k is not None else stabilizer_circuit.queue
        )

        for gate in reversed(cut_queue):

            # Invert the circuit
            gate = gate.dagger()
            if len(gate.parameters) != 0:
                # This is working for one-parameters gates right now
                angle = gate.parameters[0]
                propagator.apply(
                    getattr(tableaus, gate2tableau[gate.name])(
                        *gate.qubits, angle=angle
                    )
                )
            else:
                propagator.apply(
                    getattr(tableaus, gate2tableau[gate.name])(*gate.qubits)
                )

        return propagator
