"""Hybrid Stabilizer-MPO evolutor"""

from dataclasses import dataclass
from copy import deepcopy

import numpy as np

from qibo import Circuit


from tncdr.evolutors.tensor_network.simulator.circuit_mps import CircuitMPS
from tncdr.evolutors.tensor_network.operators.observables import PauliMPO
from tncdr.evolutors.stabilizer.pauli_string import Pauli
from tncdr.evolutors.stabilizer import tableaus

from tncdr.evolutors.utils import gate2generator, gate2tableau
from tncdr.targets.ansatze import Ansatz


@dataclass
class HybridSurrogate:
    """
    Construct an hybrid stabilizer MPO surrogate of a given quantum circuit.

    Args:
        circuit (tncdr.targets.Ansatz): given quantum circuit in the form of a 
            tncdr ansatz class.
        initial_state (qibo.models.Circuit): quantum circuit preparing the inital
            state. It has to be composed of single-qubit gates only.
    """
    ansatz: Ansatz
    initial_state: Circuit = None

    def __post_init__(self):
        # Initial state is zero by default
        if self.initial_state is None:
            self.initial_state = Circuit(self.ansatz.nqubits)

        # Add the initial state, which is |0> by default
        self._init_tn()
    
    def _init_tn(self, max_bond_dimension:int|None=None):
        """
        Initialize the HybridEvolutor's tensor network to the factorized state specified by the initial state circuit.
        """

        amplitudes = []
        for q in range(self.nqubits):

            light_circ, light_dict = self.initial_state.light_cone(q)

            # Check whether the initial state is constructed properly
            # (with one-qubit gates only)
            if len(light_dict.items()) > 1:
                raise ValueError (
                    "Ensure only 1-qubit gates compose the initial state preparation circuit."
                )

            # Add the initial state tensor
            amplitudes.append(light_circ().state())
        
        self.mps = CircuitMPS(
            n=self.nqubits,
            initial_state=np.array(amplitudes),
            max_bond_dimension=max_bond_dimension,
        )

    @property
    def nqubits(self):
        return self.ansatz.circuit.nqubits

    def expectation_from_partition(
            self, 
            n_partitions, 
            magic_gates_per_partition, 
            observable,
            return_partitions=False,
        ):
        """
        Sample a lower-magic circuit from the ansatz, and compute its expectation value wrt the observable.
        The lower-magic circuit is generated by selectively dropping magic gates with a certain rate, leaving
        only a fraction per partition. Partitioning is performed according to the Ansatz specifications.

        If specified, returns the partitions used to generate the lower-magic circuit.
        """

        # Partitionate circuit
        full_circuit, mag_layers, stab_layers = self.ansatz.partitionate_circuit(
            n_partitions=n_partitions,
            magic_gates_per_partition=magic_gates_per_partition,
        )
        
        # check the stab layers, might be wrong
        for i, magic_circuit in enumerate(mag_layers):
            for gate in magic_circuit.queue:

                generator = self._conjugate_generator(gate, stab_layers[:i])
                self.mps.pauli_rot(generator, gate.parameters[0])

        # Compute the conjugate of the observable
        new_observable = self.backpropagate_pauli(observable, sum(stab_layers, start=Circuit(self.nqubits)))

        # Collect partitions into a dictionary in case we want to return it
        if return_partitions:
            partitions = {
                "magic_layers": mag_layers,
                "stabilizer_layers": stab_layers,
                "full_circuit": full_circuit,
            }
        else:
            partitions = None

        return self.mps.expval(PauliMPO(new_observable)), partitions

    def _conjugate_generator(self, gate, stabs):
        """
        Conjugate a given gate generator by a sequence of Clifford circuits.
        """
        
        if gate.name not in ["rx", "ry", "rz"]:
            raise ValueError("tncdr currently supports only rotational gates.")
        
        generator = ''.join([gate2generator[gate.name] if q in gate.target_qubits else 'I' for q in range(self.nqubits)])
        return self.backpropagate_pauli(generator, sum(stabs, start=Circuit(self.nqubits)))

    def backpropagate_pauli(self, observable: str, stabilizer_circuit: Circuit):
        """
        Process a given Pauli string applying a `stabilizer_circuit` in 
        Heisenberg picture.
        """
        # Construct the propagator and apply the inverse of the circuit gate by gate
        propagator = Pauli(observable)
        for gate in stabilizer_circuit.invert().queue:
            propagator.apply(getattr(tableaus, gate2tableau[gate.name])(*gate.qubits))

        return propagator
