name: Tests

on:
  workflow_dispatch:
  push:
  merge_group:
  pull_request:
    types: [labeled, opened]

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'run-workflow') || github.event_name == 'push'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --with tests

      - name: Run tests with coverage
        run: poetry run pytest --cov --cov-branch --cov-report=xml

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.os }}-${{ matrix.python-version }}
          path: coverage.xml

  coverage:
    name: Upload coverage reports to Codecov
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      # Download all coverage artifacts from matrix builds
      - name: Download coverage reports
        uses: actions/download-artifact@v4
        with:
          path: ./coverage-reports

      # Merge reports (optional, if you want a single combined file)
      - name: Combine coverage reports
        run: |
          pip install coverage
          coverage combine coverage-reports/**/coverage.xml
          coverage xml -o coverage.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: MatteoRobbiati/tncdr
          files: ./coverage.xml
          fail_ci_if_error: true
